### ISSUE TITLE
Test locally?

### ISSUE THREAD

**Issue by Jonovono** [jthegedus/firebase-functions-graphql-example#2]
Have you been able to test locally?

I run `firebase serve --only functions` and when I go to /api/graphiql I am seeing:

`POST http://localhost:5002/api/graphql? 404 (Not Found)` in the JS console.

**Comment by lucasavila00** [comment]
[Firebase docs says: 
](https://firebase.google.com/docs/functions/local-emulator)
> Caution: Experimental Feature. This is an experimental feature that currently only supports emulation of **HTTPS** functions.


You're posting to http, not http**S**. That's the issue.

**Comment by jthegedus** [comment]
Thanks @degroote22 for answering this.
