### ISSUE TITLE
Mobile app support

### ISSUE THREAD

**Issue by harinanda** [jthegedus/firebase-functions-graphql-example#3]
Thanks for timely help with your article. I reach your article while browsing react-native with firebase.i am getting confusion on where to put this code in case of mobile react-native app.
Complete example is wonderful if you have time and breadth to take it.

**Comment by lucasavila00** [comment]
You'd use a GraphQL client on your mobile app to interact with your GraphQL server.
After you deploy this project to firebase it will give you back a endpoint url.
Pass this to your client library of choice and there you go.

Check this:
https://www.howtographql.com/
http://dev.apollodata.com/react/react-native.html

**Comment by jthegedus** [comment]
Thanks @degroote22 for answering this too.

@harinanda I do intend on covering Apollo Client with this series. Having said that https://www.howtographql.com/ is an amazing resource.
