### ISSUE TITLE
Graphiql queries not working

### ISSUE THREAD

**Issue by stevieoj** [jthegedus/firebase-functions-graphql-example#4]
I ran this project and everything looks nice except an issue with graphiql, it fires up as expected but queries don't work and no autocompletion. Thanks

**Comment by ersimont** [comment]
I got it partially working by changing the `endpointURL` passed to `graphiqlExpress` here: https://github.com/jthegedus/firebase-functions-graphql-example/blob/master/firebaseFunctions/graphql/server.js#L21

I made it `graphiqlExpress({ endpointURL: "graphql" })`

It still doesn't have autocomplete, and I had to make more changes to get any queries to run (by making the resolvers always return a promise), but it was a step!

**Comment by tavelli** [comment]
@ersimont thanks! with your change i get fully working based on rest of example code, including autocomplete in graphiql

**Comment by lfernando-silva** [comment]
Just to confirm, I did the @ersimont 's chages and the graphiql works on permission errors.

**Comment by simonh1000** [comment]
I'm finding I need to use `graphiqlExpress({ endpointURL: project + "/api/graphql" })` where project is `""` for deployed functions and `"/<app-name>/us-central1/"` when testing locally with `firebase serve`. As I'm changing frequently between the two this is super frustrating

**Comment by jthegedus** [comment]
I have an updated GraphQL example & blog post

post: https://medium.com/@jthegedus/graphql-on-cloud-functions-for-firebase-153fe7b02ea5
code: https://github.com/jthegedus/firebase-gcp-examples

Apologies for not getting to this sooner.
